### ISSUE TITLE
Default  hadoop_distro_url does not work

### ISSUE THREAD

**Issue by botzill** [andiveloper/ansible-hadoop#2]
```
hadoop_distro_url=http://mirrors.ukfast.co.uk/sites/ftp.apache.org/hadoop/common/hadoop-3.1.2/hadoop-3.1.2.tar.gz
```

seems to not work for me in DigitalOcean
I use instead

```
hadoop_distro_url=https://www-eu.apache.org/dist/hadoop/common/hadoop-3.1.3/hadoop-3.1.3.tar.gz
```

I guess need to find one that works for all. 

Thx.

**Comment by andiveloper** [comment]
Thanks, I've changed it to `https://www-eu.apache.org/dist/hadoop/common/hadoop-3.1.3/hadoop-3.1.3.tar.gz`
